---

- name: Create a cron job
  hosts: all

  tasks:
    - name: Schedule cron
      cron:
        name: This job is scheduled by Ansible
        minute: "0"
        hour: "10"
        day: "*"
        month: "*"
        weekday: "4"
        user: ec2-user
        job: "/home/ec2-user/cfile.sh"