---
- name: Package installation
  hosts: all
  become: yes
  vars:
   pack: httpd
   ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Install package
    dnf:
     name: "{{ pack }}"
     state: present

  - name: Start service 
    service:
     name: "{{ pack }}"
     state: started