---
- name: Install packages thru loop
  hosts: localhost
  vars:
    packages: [ftp, telnet, htop]
  become: yes

  tasks:
    - name: Install packages
      apt:
        name: '{{ packages }}'
        state: present
        update_cache: yes
