---
- name: httpd and telnet
  hosts: all
  become: yes

  tasks:

    - name: Install apache package
      dnf:
        name: httpd
        state: present

    - name: Start httpd
      service:
        name: httpd
        state: started

    - name: Install telnet
      dnf:
        name: telnet
        state: present
